#!/usr/bin/env python3
"""Derive the wallpaper accent palette and fan it out to every app's config.

Invoked by wallust-apply.sh once wallust has written its raw palette to the
ghostty include. This reads that background colour, normalises its lightness,
derives a primary + secondary accent from its hue, and writes the per-app
colour files:

    ~/.config/ghostty/wallust         normalised bg + accent cursor (edited in place)
    ~/.cache/wallust/accent           primary\\nsecondary  (read by hyprland, neovim)
    ~/.config/wofi/style.css          rendered from style.css.in
    ~/.config/waybar/style.css        rendered from style.css.in
    ~/.cache/wallust/p10k-accent.zsh  sourced by .zshrc
    ~/.cache/wallust/tmux.conf        sourced by tmux.conf
    ~/.config/stochos/config.toml     [colors] retinted in place (alpha preserved)
"""

from __future__ import annotations

import colorsys
import re
from pathlib import Path

HOME = Path.home()
GHOSTTY = HOME / ".config/ghostty/wallust"
ACCENT_FILE = HOME / ".cache/wallust/accent"
WOFI_IN = HOME / ".config/wofi/style.css.in"
WOFI_OUT = HOME / ".config/wofi/style.css"
WAYBAR_IN = HOME / ".config/waybar/style.css.in"
WAYBAR_OUT = HOME / ".config/waybar/style.css"
P10K_OUT = HOME / ".cache/wallust/p10k-accent.zsh"
TMUX_OUT = HOME / ".cache/wallust/tmux.conf"
STOCHOS = HOME / ".config/stochos/config.toml"

# Tuning knobs.
TARGET_L = 0.11             # normalised background lightness (lower = darker)
ACCENT_L = 0.64            # primary accent lightness
ANCHOR_L = 0.78           # brighter primary (p10k path anchors)
SECOND_L = 0.70            # secondary accent lightness
SECOND_HUE_SHIFT = -0.06   # secondary hue shift, toward the cooler neighbour
SAT_MIN, SAT_MAX = 0.42, 0.62  # accent saturation clamp (vivid but not neon)

HEX_RE = r"#([0-9A-Fa-f]{6})"


# --- colour helpers ----------------------------------------------------------
def hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def rgb_to_hex(r: float, g: float, b: float) -> str:
    return "#%02X%02X%02X" % (round(r * 255), round(g * 255), round(b * 255))


def hsl_hex(h: float, s: float, l: float) -> str:
    """Build a hex colour from hue/saturation/lightness (0..1)."""
    return rgb_to_hex(*colorsys.hls_to_rgb(h, l, s))


def hue_sat(hex_colour: str) -> tuple[float, float]:
    h, _, s = colorsys.rgb_to_hls(*hex_to_rgb(hex_colour))
    return h, s


def write(path: Path, content: str) -> None:
    try:
        path.write_text(content)
    except OSError:
        pass


# --- per-app outputs ---------------------------------------------------------
def render_template(src: Path, dst: Path, subs: dict[str, str]) -> None:
    try:
        text = src.read_text()
    except OSError:
        return
    for key, val in subs.items():
        text = text.replace(key, val)
    write(dst, text)


def write_p10k(accent: str, anchor: str, accent2: str) -> None:
    write(P10K_OUT,
          "# Generated by wallust-colors.py — wallpaper accent for the prompt.\n"
          f"typeset -g POWERLEVEL9K_DIR_FOREGROUND='{accent}'\n"
          f"typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='{anchor}'\n"
          f"typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='{accent}'\n"
          f"typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{{VIINS,VICMD,VIVIS,VIOWR}}_FOREGROUND='{accent}'\n"
          f"typeset -g WALLUST_ACCENT='{accent}'\n"
          f"typeset -g WALLUST_ACCENT2='{accent2}'\n")


def write_tmux(accent: str) -> None:
    # tokyo-night-tmux hardcodes a blue accent; re-set the accent-bearing options
    # after it (sourced from tmux.conf). #15161e is a dark fg for contrast.
    write(TMUX_OUT,
          "# Generated by wallust-colors.py — wallpaper accent over tokyo-night-tmux.\n"
          f'set -gq status-left "#[fg=#15161e,bg={accent},bold] '
          '#{?client_prefix,\U000f0820 ,#[dim]\U000f0902 }#[bold,nodim]#S "\n'
          f'set -gq pane-active-border-style "fg={accent}"\n'
          f'set -gq message-style "bg={accent},fg=#15161e"\n'
          f'set -gq mode-style "fg=#15161e,bg={accent}"\n')


def retint_stochos(bg_hex: str, accent: str, accent2: str) -> None:
    """Retint stochos' [colors] section, preserving each colour's alpha."""
    bg, acc, acc2 = bg_hex.lstrip("#"), accent.lstrip("#"), accent2.lstrip("#")
    roles = {
        "cell_normal": bg, "sub_cell_normal": bg, "sub_bg": bg,
        "panel_bg": bg, "hint_chip_bg": bg, "selected_bg": bg,
        "text_first": acc, "cell_highlight": acc, "border": acc,
        "crosshair": acc, "hint_text": acc,
        "text_second": acc2, "text_highlight": acc2, "cell_drag": acc2,
        "border_dragging": acc2, "hint_text_typed": acc2,
    }
    try:
        text = STOCHOS.read_text()
    except OSError:
        return
    for key, rgb in roles.items():
        text = re.sub(
            r'(^[ \t]*' + re.escape(key) + r'[ \t]*=[ \t]*")#[0-9A-Fa-f]{6}([0-9A-Fa-f]{0,2})(")',
            lambda m, c=rgb: m.group(1) + "#" + c.upper() + m.group(2) + m.group(3),
            text, count=1, flags=re.M)
    # Hint-mode colours are often absent from the user config; add them so
    # `stochos --hint` is themed too instead of using the unthemed defaults.
    for key, val in {"hint_chip_bg": bg + "EE", "hint_text": acc + "FF",
                     "hint_text_typed": acc2 + "FF"}.items():
        if not re.search(r'^[ \t]*' + re.escape(key) + r'[ \t]*=', text, re.M):
            text = re.sub(r'^\[colors\][ \t]*\n',
                          lambda m, k=key, v=val: m.group(0) + f'{k} = "#{v.upper()}"\n',
                          text, count=1, flags=re.M)
    write(STOCHOS, text)


def main() -> None:
    text = GHOSTTY.read_text()

    # 1. Normalise the background lightness to a fixed dark target, keeping hue.
    def fix_bg(m: re.Match) -> str:
        h, s = hue_sat(m.group(1))
        return "background = " + hsl_hex(h, s, TARGET_L)
    text = re.sub("background = " + HEX_RE, fix_bg, text, count=1)

    # 2. Derive accents from the wallpaper's DOMINANT hue (the background) — not
    #    wallust's cursor, which is often a clashing highlight.
    m = re.search("background = " + HEX_RE, text)
    bg_hex = m.group(1) if m else "11121b"
    h, s = hue_sat(bg_hex)
    s = min(max(s, SAT_MIN), SAT_MAX)
    accent = hsl_hex(h, s, ACCENT_L)                              # primary
    anchor = hsl_hex(h, s, ANCHOR_L)                              # brighter primary
    accent2 = hsl_hex((h + SECOND_HUE_SHIFT) % 1.0, s, SECOND_L)  # secondary

    # 3. Point ghostty's cursor at the accent too, then persist.
    text = re.sub("cursor-color = " + HEX_RE, "cursor-color = " + accent, text, count=1)
    GHOSTTY.write_text(text)

    # 4. Fan out to every app.
    write(ACCENT_FILE, f"{accent}\n{accent2}\n")
    r, g, b = (int(accent[i:i + 2], 16) for i in (1, 3, 5))
    br, bgc, bb = (int(bg_hex[i:i + 2], 16) for i in (0, 2, 4))
    render_template(WOFI_IN, WOFI_OUT,
                    {"__ACCENT_RGB__": f"{r}, {g}, {b}", "__BG_RGB__": f"{br}, {bgc}, {bb}"})
    render_template(WAYBAR_IN, WAYBAR_OUT, {"__ACCENT__": accent})
    write_p10k(accent, anchor, accent2)
    write_tmux(accent)
    retint_stochos(bg_hex, accent, accent2)


if __name__ == "__main__":
    main()
