$font = Iosevka

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = easeOut, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 5, easeOut
    animation = fadeOut, 1, 3, easeOut
    animation = inputFieldDots, 1, 3, easeOut
}

background {
    monitor =
    color = rgba(0, 0, 0, 0.35)
}

# Clock
label {
    monitor =
    text = cmd[update:1000] LC_ALL=C date +%H:%M
    font_size = 60
    font_family = $font
    color = rgba(235, 235, 240, 0.92)

    position = 0, 65
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] LC_ALL=C date +'%A, %B %-d'
    font_size = 15
    font_family = $font
    color = rgba(200, 200, 210, 0.65)

    position = 0, 10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 195, 38
    outline_thickness = 2
    inner_color = rgba(20, 20, 25, 0.6)

    outer_color = rgba(220, 220, 230, 0.25)
    check_color = rgba(180, 230, 200, 0.9)
    fail_color = rgba(240, 130, 140, 0.85)

    font_color = rgba(220, 220, 230, 1.0)
    fade_on_empty = true
    rounding = 19

    font_family = $font
    placeholder_text = <span foreground="##909098">unlock</span>
    fail_text = $PAMFAIL

    dots_spacing = 0.35
    dots_size = 0.3

    position = 0, -78
    halign = center
    valign = center
}
